# remap bind key from 'Ctrl-b' to 'Ctrl-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set the default terminal type
set -g default-terminal "screen-256color"

# source config with C-a + r
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# enable mouse mode (>tmux 2.1)
# clickable windows, panes, resizable panes
set -g mouse on

# turn off all the bell sounds
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# statusbar
# xterm colors    : https://jonasjacek.github.io/colors/
# strftime format : https://devhints.io/datetime
set -g status-position bottom
set -g status-style 'bg=colour235 fg=colour255'
set -g status-left "  "
set -g status-right "#[bg=colour235,fg=colour255] %a %b %e #[bg=colour235,fg=colour255] %H:%M:%S  "
set -g status-right-length 50
set -g status-left-length 50

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# panes colors
set -g pane-border-style 'bg=default fg=colour19'
set -g pane-active-border-style 'bg=default fg=colour172'

# message styling
set -g message-style 'fg=colour255 bg=colour62'
